apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: consumer
    soft: python
  name: moadreplicataset-consumer
spec:
  replicas: 1                     # Nombre d'instance de la charge de travail à déployer
  selector:
    matchLabels:
      app: consumer
      soft: python
  template:                       # template: à partir de là, les attributs qui suivent seront ceux du Pod qui va être créé
    metadata:
      labels:
        app: consumer
        soft: python
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/consumer-image-2024:Garrag-Bahand
        name: moadcontainerfromreplica
        resources:                # Correction ici : Utilisez 'resources' au lieu de 'ressources'
          requests:
            memory: "56Mi"        # Assurez-vous de spécifier la bonne unité (Mi pour Mégabytes)
            cpu: "50m"            # '50m' signifie 50 milli-CPU
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
