apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: Calculatrice-front
    soft: nginx
  name: moadreplicataset-front
spec:
  replicas: 1                     # Nombre d'instance de la charge de travail à déployer
  selector:
    matchLabels:
      app: Calculatrice-front
      soft: nginx
  template:                       # template: à partir de là, les attributs qui suivent seront ceux du Pod qui va être créé
    metadata:
      labels:
        app: Calculatrice-front
        soft: nginx
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/front-image-2024:GarragBahand
        name: moadcontainerfromreplica
        resources:                # Correction ici: 'resources' et non 'ressources'
          requests:
            memory: "56Mi"        # Assurez-vous de spécifier la bonne unité (Mi pour Mégabytes)
            cpu: "50m"            # '50m' signifie 50 milli-CPU
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
