apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: message-queue-service
    soft: rabbitmq
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
  selector:
    app: message-queue
    soft: rabbitmq
  type: ClusterIP  