apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moad-ingress
  namespace: garrag-bahand
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ""   ## DNS => nom de domaine => 35.205.81.63
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moadservice-front
            port:
              number: 8080