apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: Bdd       # Correspond aux labels définis dans le ReplicaSet
    soft: redis
  ports:
  - protocol: TCP
    port: 6379                    # Port accessible à l'extérieur
    targetPort: 6379            # Port sur lequel le conteneur écoute
  type: ClusterIP                 # Service accessible uniquement dans le cluster
