# Utiliser une image de base officielle de Nginx
FROM nginx:alpine

# Copier les fichiers de l'application dans le répertoire par défaut de Nginx
COPY . /usr/share/nginx/html

# Exposer le port sur lequel Nginx s'exécute
EXPOSE 80