apiVersion: v1
kind: Service
metadata:
  name: moadservice-bdd
spec:
  selector:
    app: Bdd       # Correspond aux labels définis dans le ReplicaSet
    soft: redis
  ports:
  - protocol: TCP
    port: 80                    # Port accessible à l'extérieur
    targetPort: 5000            # Port sur lequel le conteneur écoute
  type: ClusterIP                 # Service accessible uniquement dans le cluster
